---
apiVersion: v1
kind: Pod
metadata:
  name: csirbd-demo-pod
  namespace: default
spec:
  containers:
   - name: fio
     image: fio
     volumeMounts:
       - name: mypvc
         mountPath: /mnt/fio
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: rbd-pvc
       readOnly: false
