apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: fio-benchmark
  namespace: my-ripsaw
spec:
  elasticsearch:
    server: 10.0.78.167
    port: 9200
  clustername: env_ocpversion_ocsversion
  test_user: interface_iopattern
  workload:
    name: "fio_distributed"
    args:
      prefill: false
      samples: 3
      servers: 3
      pin_server: ''
      jobs:
        - write
        - read
      bs:
        - 1024KiB
        - 64KiB
      numjobs:
        - 1
      iodepth: 4
      read_runtime: 60
      read_ramp_time: 5
      filesize: 80GiB
      log_sample_rate: 1000
      storageclass: ocs-storagecluster-ceph-rbd
      storagesize: 100Gi
      rook_ceph_drop_caches: True
      rook_ceph_drop_cache_pod_ip:
        - server1
        - server2
        - server3
#######################################
#  EXPERT AREA - MODIFY WITH CAUTION  #
#######################################
#  global_overrides:
  job_params:
    - jobname_match: w
      params:
        - fsync_on_close=1
        - create_on_open=1
        - runtime={{ fiod.read_runtime }}
        - ramp_time={{ fiod.read_ramp_time }}
    - jobname_match: read
      params:
        - time_based=1
        - runtime={{ fiod.read_runtime }}
        - ramp_time={{ fiod.read_ramp_time }}
    - jobname_match: rw
      params:
        - rwmixread=50
        - time_based=1
        - runtime={{ fiod.read_runtime }}
        - ramp_time={{ fiod.read_ramp_time }}
    - jobname_match: readwrite
      params:
        - rwmixread=50
        - time_based=1
        - runtime={{ fiod.read_runtime }}
        - ramp_time={{ fiod.read_ramp_time }}
#    - jobname_match: <search_string>
#      params:
#        - key=value