---
apiVersion: v1
kind: Pod
metadata:
  name: {{pod_name | default("nginx1") }}
  namespace: {{ project_name | default("default")}}
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - name: mypvc
         mountPath: /var/lib/www/html
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: {{ pvc_name | default ("test-rbd-device")}}
       readOnly: false
