---
apiVersion: 'storage.k8s.io/v1'
kind: StorageClass
metadata:
  name: {{sc_name | default('ocs-qe')}}
parameters:
  blockPool: {{blockpool | default('rbd')}}
  clusterNamespace: openshift-storage
  fstype: xfs
provisioner: 'ceph.rook.io/block'
reclaimPolicy: {{reclaimPolicy | default('Delete')}}
volumeBindingMode: Immediate
